import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // Auto-generated stub modules re-export missing types as `any` to bridge
    // the untyped shadcn-extraction source. Disable no-explicit-any etc.
    files: [
      "src/lib/lucide-react.ts",
      "src/lib/stub-empty.ts",
      "src/lib/**/*.ts",
      "src/hooks/use-*.ts",
      "src/registry/**/*.ts",
      "src/registry/**/*.tsx",
      "src/styles/**/*.tsx",
      "src/app/(app)/**/*.tsx",
      "src/components/create/cards/**/*.tsx",
      "src/components/create/[a-z]*.tsx",
      "src/components/create/[a-z]*-nav.tsx",
      "src/components/create/[a-z]*-display.tsx",
      "src/components/create/[a-z]*-button.tsx",
      "src/components/create/[a-z]*-code-viewer.tsx",
      "src/components/create/[a-z]*-chart.tsx",
      "src/components/create/[a-z]*-image.tsx",
      "src/components/create/[a-z]*-scroller.tsx",
      "src/components/create/[a-z]*-tab*.tsx",
      "src/components/create/[a-z]*-code-tabs.tsx",
      "src/components/create/[a-z]*-copy-button.tsx",
      "src/components/create/[a-z]*-theme-picker.tsx",
      "src/components/create/[a-z]*-provider.tsx",
      "src/components/create/announcement.tsx",
      "src/components/create/block-display.tsx",
      "src/components/create/block-image.tsx",
      "src/components/create/block-viewer.tsx",
      "src/components/create/blocks-nav.tsx",
      "src/components/create/callout.tsx",
      "src/components/create/charts-nav.tsx",
      "src/components/create/code-block-command.tsx",
      "src/components/create/code-collapsible-wrapper.tsx",
      "src/components/create/code-tabs.tsx",
      "src/components/create/color-format-selector.tsx",
      "src/components/create/color-palette.tsx",
      "src/components/create/color.tsx",
      "src/components/create/colors-nav.tsx",
      "src/components/create/command-menu.tsx",
      "src/components/create/component-preview-tabs.tsx",
      "src/components/create/component-preview.tsx",
      "src/components/create/component-source.tsx",
      "src/components/create/component-wrapper.tsx",
      "src/components/create/components-list.tsx",
      "src/components/create/directory-add-button.tsx",
      "src/components/create/directory-list.tsx",
      "src/components/create/directory-search.tsx",
      "src/components/create/docs-base-switcher.tsx",
      "src/components/create/docs-breadcrumb.tsx",
      "src/components/create/docs-copy-page.tsx",
      "src/components/create/docs-page-links.tsx",
      "src/components/create/docs-sidebar.tsx",
      "src/components/create/docs-toc.tsx",
      "src/components/create/examples-nav.tsx",
      "src/components/create/github-link.tsx",
      "src/components/create/language-selector.tsx",
      "src/components/create/main-nav.tsx",
      "src/components/create/markdown.tsx",
      "src/components/create/message-animated.tsx",
      "src/components/create/message-parts.tsx",
      "src/components/create/mobile-nav.tsx",
      "src/components/create/nav-header.tsx",
      "src/components/create/nav-user.tsx",
      "src/components/create/open-in-v0-button.tsx",
      "src/components/create/open-in-v0-cta.tsx",
      "src/components/create/page-header.tsx",
      "src/components/create/page-nav.tsx",
      "src/components/create/site-config.tsx",
      "src/components/create/site-footer.tsx",
      "src/components/create/site-header.tsx",
      "src/components/create/tailwind-indicator.tsx",
      "src/components/create/theme-provider.tsx",
    ],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-empty-object-type": "off",
      "@typescript-eslint/ban-ts-comment": "off",
      "react-hooks/set-state-in-effect": "off",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
  ]),
]);

export default eslintConfig;
